<div style = 'z-index:30;position: relative; height:7vw;left:0px;top:0px;' class = 'full-width'>
	<div style = 'position:absolute; height:100%;left:0px;top:0px;background-color:#7e5785;opacity:0.9' class = 'full-width' id = 'title_login'>
	</div>
<div  style = 'display:inline;  padding-left:50%;margin-left:-5.8vw;z-index:999'>
		<a class = 'playbutton' style = 'opacity:1' href="<?php echo base_url() ?>">
			<img src = "<?php echo base_url(WEB_IMAGES.'Ginko-Logo.png');?>" style = 'height:5vw;top:1vw;position:absolute;'>
		</a>
		
    </div>            
</div>

<div class="chat_description_content">
	<h3>Ginko Sharing Contest Official Rules</h3>
	<p>NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN. A PURCHASE OR PAYMENT WILL NOT INCREASE YOUR CHANCES OF WINNING. CONTEST OPEN TO LEGAL RESIDENTS OF THE UNITED STATES OTHER THAN THOSE IN NEW YORK AND FLORIDA, EIGHTEEN AND OVER, WHO ATTENDED A FOUR-YEAR ACCREDITED UNIVERSITY IN THE UNITED STATES DURING THE CONTEST PERIOD. ALL PRIZES MAY NOT BE AWARDED. VOID WHERE PROHIBITED.</p>
	<p><b>By freely entering the Contest, you, the entrant, agree to every element, aspect, description, and definition within these Official Rules.</b></p>
	<p><b>ELIGIBILITY:</b> This Contest is open to legal residents of the United States other than those in New York and Florida, eighteen (18) years of age or older at the time of entry, who attended a four-year accredited university in the United States during the Contest Period (defined below). Void where prohibited.</p>
	<p><b>The following are not eligible:</b> Anyone who did not attend a four-year accredited university located in the United States during the Contest Period is not eligible.  In addition, employees, agents, agent staff, officers, and directors (and their immediate family members) of Ginko LLC, including its affiliated companies, subsidiaries, licensees, distributors, dealers, retailers, contractors, printers, web design, and advertising and promotion agencies, and any and all other companies or individuals associated with the administration, development, fulfillment and execution of this Contest (collectively, "Promotion Parties") are not eligible to participate. The term "immediate family member" includes spouses, grandparents, parents, siblings, children, and grandchildren and "step" of each. In addition, those living in the same households (those persons whether related or not who live in the same residence for at least three (3) months during the twelve month period preceding the start date of the Contest) are not eligible to participate in this Contest. </p>
	<h4>1. SPONSORS</h4>
	<p>The Ginko Sharing Contest (the “Contest”) is sponsored by Ginko LLC, PO Box 250575, West Bloomfield, MI 48325 (the “Sponsor”).  Sponsor is responsible for the collection, submission and processing of entries and the overall administration and execution of the Contest.</p>
	<h4>2. CONTEST PERIOD</h4>
	<p>The Contest begins at 12:00:00 AM Central Standard Time ("CST") on September 8, 2015 and ends at 11:59:59 PM CST on December 31, 2015, or until each category has reached the required number of winners, whichever occurs first ("Contest Period").</p>
	<h4>3. HOW TO ENTER</h4>
	<p>To enter the Contest, simply download the Ginko mobile application (the “App”) through Google Play or the App Store before or during the Contest Period.  Any person who downloads the App and is eligible for the contest during the Contest Period will automatically be entered in the Contest pursuant to Ginko’s terms of use available at www.ginko.mobi.  If you are a winner of the contest but elect not to receive the prize, you may reject the prize at time of the notification of being the winner of that prize.   Use of the App is subject to any applicable Google, Inc. or Apple, Inc. restrictions. </p>
	<p>Limit of one (1) entry per person during the Contest Period. Entrants may enter the Contest only one (1) time. Any attempt to obtain more than one (1) entry, may lead to disqualification (as determined by Sponsors in their sole discretion). No substitutes for the official entry method may be used to enter the Contest, and Sponsors will not accept entries by email, fax, or any other way other than the methods listed above. All entries are the property of Promotion Parties. If there is a dispute as to who submitted an entry, the Sponsors will make this determination at their sole discretion.</p>
	<h4>4. CONTEST TERMS OF SUBMISSION</h4>
	<p>Sponsor reserves the right to cancel, suspend and/or modify the Contest, or any part of it, if any fraud, technical failures or any other factor impairs the integrity or proper functioning of the Contest, as determined by Sponsor in its sole discretion. If, for reasons beyond the control of Sponsor (including, but not limited to, tampering or computer virus infection), the Contest is not capable of being executed as originally planned, Sponsor, at its sole discretion, reserves the right to cancel or modify the Contest, without liability. Sponsor reserves the right, in its sole discretion, to disqualify any individual it finds to be tampering with the entry process or the operation of the Contest or to be acting in violation of these Official Rules or in an unsportsmanlike or disruptive manner and void all associated entries.  Sponsor’s failure to enforce any term of these Official Rules shall not constitute a waiver of that provision.  All interpretations of these Official Rules and decisions by the Sponsor are final.</p>
	<p>ANY ATTEMPT BY AN ENTRANT OR ANY OTHER INDIVIDUAL TO DELIBERATELY UNDERMINE THE LEGITIMATE OPERATION OF THE CONTEST IS A VIOLATION OF CRIMINAL AND CIVIL LAWS, AND SHOULD SUCH AN ATTEMPT BE MADE, PROMOTION PARTIES RESERVE THE RIGHT TO SEEK DAMAGES AND OTHER REMEDIES (INCLUDING ATTORNEYS’ FEES) FROM ANY SUCH ENTRANT TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
	<h4>5. HOW WINNERS ARE SELECTED</h4>
	<p>The Contest Prize Winners (each, a “Winner”) will be determined based on the first Winner(s) to reach the minimum required shares for each prize category.  There are four (4) prize categories, and a total of one hundred thirty-six (136) Winners are possible. Entrant’s may only win one (1) prize.  If an entrant qualifies to win a prize from more than one of the Prize Categories, that entrant will receive the prize associated with the higher category.  Odds of winning depend on a number of factors, including but not limited to each Entrant’s usage of the App and the number of eligible entries received.  Only prizes earned during the Contest Period will be awarded.</p>
	<h4>6. Prize Categories</h4>
	<p>Each entrant will be eligible to win one (1) prize from the following prize categories (the “Prize Categories”) during the Contest Period. </p>
	<p class="sub_txt"><span class="under_text">Category 1 – Semester Tuition.</span>  The first entrant to use the App and make 1,000 contact shares (“Shares”) will receive one semester’s worth of tuition, up to $6,500.00 [six thousand five hundred US dollars].  There is a limit of one (1) Winner* for Category 1.  The Approximate Value of the Category 1 Prize is $6,500.00 [six thousand five hundred US dollars]. </p>
	<p class="sub_txt"><span class="under_text">Category 2 – Macbook.</span>  The first ten (10) eligible entrants to use the App and make 700 Shares will each receive a Macbook.  There is a limit of ten (10) Winners* for Category 2.   The Approximate Retail Value of each Macbook is $900.00 [nine hundred US dollars]. </p>
	<p class="sub_txt"><span class="under_text">Category 3 – Visa Gift Card.</span>  The first twenty-five (25) eligible entrants to use the App and make 400 Shares will each receive a Visa gift card worth $50 USD.  There is a limit of twenty-five (25) Winners* for Category 3.  The Approximate Retail Value of each Visa gift card is $50 [fifty US dollars]. </p>
	<p class="sub_txt"><span class="under_text">Category 4 – Netflix Gift Card.</span>  The first one hundred (100) eligible entrants to use the App and make 250 Shares will each receive a Netflix gift card worth $30 USD.  There is a limit of one hundred (100) Winners* for Category 4.  The Approximate Retail Value of each Netflix gift card is $30 [thirty US dollars].</p>
	<p>One “Share” is defined as using the App to exchange your individual contact information through the App with one other individual.  Only Shares during the Contest Period are considered.  Limit of one Share to one individual.  Sponsor reserves the right to audit a Winner’s shared contact list to evaluate the validity of each user profile that constituted a single Share.  Entrants who are found to have created or shared their contact information with fake user profiles may be disqualified from the Contest in Sponsor’s sole reasonable discretion.  By entering the Contest, entrant agrees to grant Sponsor the right to conduct such an audit for the purposes specified herein.  </p>
	<p>If at the end of the Contest Period, all potential Prizes have not been earned, an entrant’s eligibility to win a particular prize shall expire.  For the avoidance of doubt and by way of example only, if at the conclusion of the Contest Period, there are no entrants who have reached 1,000 Shares to qualify for the Category 1 Prize, than Sponsor shall not be required to award the Category 1 Prize to any entrant.  Similarly, if, for example, only two entrants have reached 700 Shares to qualify for the Category 2 Prize, only two (2) Winners will receive the Category 2 Prize and the remaining eight (8) Category 2 Prize’s shall not be awarded.  </p>
	<p>Except where prohibited by law, unclaimed or unearned Prizes may not be awarded.  </p>
	<p>* Entrant’s may only win one (1) prize in one Prize Category.  If an entrant qualifies to win a prize from more than one of the Prize Categories, that entrant will receive the prize associated with the higher category.  For instance, if an entrant is the first to 250 contact shares, and also the first to 400 Shares, that entrant will win one of the $50 Visa cards given to Category 3 Winners.  However, if an entrant is the first to 250 contact shares but the 26th to 400 Shares, that entrant will only receive the $30 Netflix card given to Category 4 Winners.  </p>
	<h4>7. WINNERS ANNOUNCED</h4>
	<p>On or about January 1, 2016, the Sponsor will determine the number of Contest Winners for each Prize Category.  </p>
	<h4>8. PRIZES</h4>
	<h5>1. Assignability</h5>
	<p>Winners cannot assign or transfer their prizes to any other person or entity.  Any expenses not stated herein (including, but not limited to, federal, state and local taxes or any other applicable fees or costs not expressly identified above that are related to participation in the Contest and the acceptance and/or use the Prizes) are the sole responsibility of the applicable recipient.  </p>
	<h5>2. Prize Acceptance</h5>
	<p>Sponsor is solely responsible for shipment of Prizes to each Winner.  Sponsor will make every effort to ensure Prizes are delivered on time, but cannot be held responsible for lost, delayed, or incomplete shipment of Prizes. </p>
	<p>If a potential Winner is unwilling or unable to accept the prize requirements, or the potential Winner refuses to allow Sponsor to audit the potential Winner’s Shares, potential Winner shall be disqualified and all privileges otherwise due shall be terminated and an alternative Winner may be chosen from among all of the remaining eligible entries received if time permits in Sponsors’ sole discretion. </p>
	<h5>3. Notification</h5>
	<p>The potential Winner will be notified by e-mail or phone between January 1, 2016 and January 8, 2016 and must respond to the notification by telephone or email within five (5) business days of Sponsor’s issuance of notification. Failure to respond completely and within the designated timeframe may result in disqualification and, an alternate Winner may be selected from among all remaining applicable Eligible Entries received if time permits in Sponsor’s sole discretion.</p>
	<h5>4. Winner Verification & Acceptance</h5>
	<p>Winners may be required to prove eligibility, including, without limitation, proof of age and residence, within five (5) days of being notified as a potential Winner. In the event of non-compliance by a potential Winner, if he/she is found to be ineligible, if he/she cannot or does not comply with these Official Rules or if his/her prize or prize notification is returned as undeliverable, such potential Winner shall be disqualified and all privileges otherwise due as a Winner shall be terminated and an alternative potential Winner may be chosen from among all of the remaining Eligible Entries received if time permits in Sponsors' sole discretion. Sponsors are not responsible for any change in Entrant's mailing address, email address and/or phone number. Each potential Winner must sign within five (5) days of receipt of such documents from Sponsor: (a) a declaration of eligibility and release of the Promotion Parties and their respective officers, directors, employees, agents, members, affiliated companies and subsidiaries, from any and all liability, loss, claims, demands, and causes of action for personal injury and/or damage, theft, loss, or any other harm suffered in connection with this Contest or the use/misuse or acceptance of any prize or any portion thereof to be eligible for a Prize; and (b) except where prohibited by law, a promotional release granting the Promotion Parties the right to use their name and likeness for advertising and publicity purposes without additional compensation. </p>
	<p>Entry into this Contest constitutes agreement to sign such releases. Each potential Winner also must acknowledge that Promotion Parties has not and will not obtain or provide insurance of any kind relating to the Prizes and that each potential Winner will be responsible for obtaining and paying for any property or other form of insurance relating to the Prizes. Each potential Winner must also complete any additional legal documents provided by Sponsor (or third parties on its behalf, if applicable) with respect to the Prizes and return them as instructed within the timeframe specified by the Sponsor or the potential Winner may forfeit Prizes at the Sponsor’s sole discretion. All decisions of the Sponsor relating to the Contest are final. The Sponsor expressly reserves the right to delay the announcement of the Winners for creative or technical reasons or for any other reason the Sponsor deems necessary.</p>
	<h5>5. GENERAL CONDITIONS</h5>
	<p>Sponsor reserves the right to amend the Official Rules at any time in their sole discretion due to amendment and/or adoption of new or existing laws and/or regulations regarding the administration, operation or for any other reason in the sound discretion of the Sponsor. Please check the Official Rules posted on the Ginko Website, www.ginko.mobi for any changes/modifications.</p>
	<p>All costs and expenses not specifically listed herein are solely each Winner's responsibility. Winners are solely responsible to report and pay any applicable taxes on their prize. Each Winner must supply Sponsor’s with his/her social security number for tax purposes. An IRS Form 1099 will be issued in the name of each Winner for the actual value of the prize received. By participating, Entrants agree to these Official Rules which are final and binding in all respects. Unclaimed or unearned prizes will not be awarded. </p>
	<h4>9. LIMITATIONS OF LIABILITY AND RELEASE</h4>
	<p>Entrants agree that the Promotion Parties (a) shall not be responsible or liable for any losses, damages or injuries of any kind resulting from participation in the Contest or any Contest-related activity, or from Entrants' acceptance, receipt, possession and/or use or misuse of the prize(s), and (b) have not made any warranty, representation or guarantee express or implied, in fact or in law, with respect to the prize(s), including, without limitation, to such prize's quality or fitness for a particular purpose. No liability or responsibility is assumed by Sponsor or Promotion Parties resulting from any user's participation in or attempt to participate in the Contest or ability or inability to upload or download any information in connection with participating in the Contest. No responsibility or liability is assumed by the Sponsor or Promotion Parties for technical problems or technical malfunction arising in connection with any of the following occurrences which may affect the operation of the Contest: hardware or software errors; faulty computer, telephone, cable, satellite, network, electronic, wireless or Internet connectivity or other online communication problems; errors or limitations of any mobile data or Internet service providers, servers, hosts or providers; garbled, jumbled or faulty data transmissions; failure of any e-mail transmissions to be sent or received; lost, late, delayed or intercepted e-mail transmissions or entries; unauthorized human or non-human intervention of the operation of the Contest, including without limitation, unauthorized tampering, hacking, theft, virus, bugs, worms; or destruction of any aspect of the Contest, or loss, miscount, misdirection, inaccessibility or unavailability of an email account used in connection with the Contest. Sponsor and Promotion Parties are not responsible for any typographical errors in the announcement of prizes or these Official Rules, or any inaccurate or incorrect data contained on the Web Site hosting the Official Rules. Use of Web Site is at user's own risk. Sponsor and Promotion Parties are not responsible for any personal injury or property damage or losses of any kind which may be sustained to user's or any other person's computer equipment resulting from participation in the Contest, use of the Web Site or the download of any information from the Web Site. By participating in the Contest, Entrants agrees to release and hold Sponsor and Promotion Parties harmless from any and all claims, damages or liabilities arising from or relating to such Entrant's participation in the Contest.</p>
	<h4>10.	PUBLICITY</h4>
	<p>Except where prohibited, participation in the Contest and acceptance of Prize constitutes each winner's permission for Sponsor and Promotion Parties to use his/her name, address (city and state only), likeness, photograph, picture, portrait, voice, biographical information, and/or any statements made by each Winner regarding the Contest or Promotion Parties for advertising or promotional purposes without notice or additional compensation. </p>
	<h4>11.	DISPUTES</h4>
	<p>Except where prohibited, Entrant agrees that: (1) any and all disputes, claims and causes of action arising out of or connected with this Contest or any prize awarded shall be resolved individually in Chicago, Illinois; (2) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with entering this Contest, but in no event attorneys' fees or court costs; and (3) under no circumstances will Entrant be permitted to obtain awards for, and Entrant hereby waives all rights to claim, indirect, punitive, incidental and consequential damages and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased. All issues and questions concerning the construction, validity, interpretation and enforceability of these Official Rules, or the rights and obligations of the Entrant and Sponsor in connection with the Contest, shall be governed by, and construed in accordance with, the laws of the State of Illinois without giving effect to any choice of law or conflict of law rules (whether of the State of Illinois or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the State of Illinois. </p>
	<h4>11.	Apple and Google</h4>
	<p>This Contest is in no way sponsored, endorsed or administered by, or associated with, Apple, Inc. or Google, Inc.  </p>
	<h4>12.	WINNERS' LIST/RULES REQUEST</h4>
	<p>For Official Rules, please visit www.ginko.mobi or send an email to info@ginko.mobi.  If you have any questions about the Contest, Winner names, or Official Rules, please send an email to: info@ginko.mobi. </p>
</div>

<div style = 'background-color:#89cb60; height:10vw; bottom:18vw; margin-top: -3vw;' class = 'full-width' align = 'center'>
  <table style="width:100%;text-align: center;font-size: 2vw;color:white;padding-bottom:3%;padding-top:2.2%;font-family:HelveticaLight">
    <tbody>
      <tr>
        <td style = 'width: 25%;cursor:pointer;'><a href="<?php echo base_url(); ?>officialrules" style="color: white; text-decoration: none;">Official Rules</a></td>
        <td style = 'width: 25%;border-right:1px solid white;border-left:1px solid white;cursor:pointer;'><a href="<?php echo base_url(); ?>terms" style="color: white; text-decoration: none;">Terms of Use</a></td>
        <td style = 'width: 25%;border-right:1px solid white;cursor:pointer;'><a href="<?php echo base_url(); ?>privacypolicy" style="color: white; text-decoration: none;">Privacy Policy</a></td>
        <td style = 'width: 25%;cursor:pointer;'><a href="<?php echo base_url(); ?>aboutus" style="color: white; text-decoration: none;">About Us</a></td>
      </tr>
    </tbody>
  </table>
</div>
<div style = 'background-color:white; height:18vw; bottom:0px; ' class = 'full-width' align = 'center'>

	<table style="width:80%;text-align: center;font-size: 2vw;color:white;padding-top:0px; padding-bottom:0px">
    <tbody>
      <tr>
        <td style = 'text-align:right'><a href = 'https://itunes.apple.com/us/app/ginko/id1029413955?ls=1&mt=8'><img src = "<?php echo base_url(WEB_IMAGES.'footer 1.png');?>" style = 'width:50%'></a></td>
        <td style = 'text-align:left'><a href = 'https://play.google.com/store/apps/details?id=com.ginko.ginko'><img src = "<?php echo base_url(WEB_IMAGES.'footer 2.png');?>" style = 'width:50%'></a></td>
      </tr>
      <tr>
      	<td colspan = 2 align = 'center'>
        	
            <div class = 'cell_content' style = 'font-size:2vw; color:black;display:block'>
            	Ginko LLC © 2014
            </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>	

