<div style = 'z-index:30;position:relative; height:7vw;left:0px;top:0px;' class = 'full-width'>
	<div style = 'position:absolute; height:100%;left:0px;top:0px;background-color:#7e5785;opacity:0.9' class = 'full-width' id = 'title_login'>
	</div>
<div  style = 'display:inline;  padding-left:50%;margin-left:-5.8vw;z-index:999'>
		<a class = 'playbutton' style = 'opacity:1' href="<?php echo base_url() ?>">
			<img src = "<?php echo base_url(WEB_IMAGES.'Ginko-Logo.png');?>" style = 'height:5vw;top:1vw;position:absolute;'>
		</a>
		
    </div>            
</div>

<div class="chat_description_content">
	<h3>TERMS OF USE & END USER LICENSE AGREEMENT</h3>
	<p>Last Updated:   September 23, 2015</p>
	<p>The mission of GINKO is to simplify the management of your contacts and to assist in keeping contact information current. To achieve our mission, we make contact management services available through our mobile applications and website to help you manage your contact information and stay in touch with family, friends and business associates.</p>
	<p>These terms of use and end user license agreement (“agreements”) governs your use of our mobile applications, website, its services/products and will govern your ongoing use of those services. Said services are owned and operated by GINKO, LLC, a Michigan based Limited Liability Company.</p>
	<p>You agree that by registering on GINKO, or by using our mobile applications, including our website, premium services, or other information provided as part of the GINKO services (collectively “GINKO” or the “Services”), you are entering into a legally binding agreement with GINKO LLC.</p>
	<p>By clicking the ‘signup’ or ‘done’ buttons, you agree to the terms of this agreement. If you do not want to become a User, do not accept this Agreement, do NOT click the ‘signup’ or ‘done’ buttons and do not access, view, download or otherwise use any GINKO mobile application, webpage, information or services. By becoming a User you acknowledge that you have read and understood the terms and conditions of this Agreement and that you agree to be bound by all of its provisions.</p>
	<p>This Service is intended to be accessed and used by individuals from within the United States of America only, and GINKO disclaims any representations and/or warranties it makes in this Agreement which may apply to individuals who access the Service from other countries.  By accessing and using the Services, you represent, warrant, and affirm that you are at least 18 years of age, an emancipated minor, or have acquired a parent or guardian’s consent.  You hereby affirm that you are, at a minimum and without exception, 13 years old.  The Services are not intended to be accessed or utilized by children less than 13 years of age.  If your use of the Services are illegal or otherwise prohibited in the jurisdiction where you are located, you are prohibited from accessing and utilizing the Services.</p>
	<p>If you are entering into this Agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity and its affiliates to these terms and conditions, in which this case the terms "you" or "your" shall refer to such entity and its affiliates. If you do not have such authority, or if you do not agree with these terms and conditions, you must not accept this agreement and may not use the services.</p>
	<p>You may not access the services of using our mobile software or web-based applications for exchanging, displaying and managing contact information if you are our direct competitor, except with our prior written consent.  In addition, you may not access the services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</p>
	<p>This is effective between you and us as of the date of you accepting this Agreement.</p>
	<p>Table of Contents</p>
	<ul class="underline_list">
		<li>Definitions</li>
		<li>Purchased Services </li>
		<li>Use of the Services </li>
		<li>Third-Party Providers </li>
		<li>Proprietary Rights </li>
		<li>Warranties and Disclaimers </li>
		<li>Indemnification </li>
		<li>Limitation of Liability </li>
		<li>Term and Termination </li>
		<li>Who You Are Contracting With, Notices, Governing Law and Jurisdiction</li>
		<li>General Provisions</li>
	</ul>
	<h4>1. DEFINITIONS</h4>
	<p>"<b>Affiliate</b>" means any entity which directly or indirectly controls, is controlled by, or is under common control with the subject entity. "Control," for purposes of this definition, means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity.</p>
	<p>"<b>Malicious Code</b>" means viruses, worms, time bombs, Trojan horses and other harmful or malicious code, files, scripts, agents or programs.</p>
	<p>"<b>Services</b>" means the online, mobile or web-based software application for exchanging, displaying and managing contact information and platform provided by Us via the App Store, Google Play, other mobile app download sites, www.ginko.mobi and/or including associated offline components, but excluding Third Party Applications.</p>
	<p>"<b>Third-Party Applications</b>" means online, Web-based and mobile applications and offline software products that are provided by third parties, interoperate with the Services, and are identified as third-party applications, including but not limited to those listed on www.ginko.mobi.</p>
	<p>"<b>Users</b>" means individuals who are authorized by Us to use the Services, for whom subscriptions to a Service have been granted free of charge or purchased, and who have been supplied user identifications and passwords by You (or by Us at Your request). Users may include but are not limited to your employees, consultants, contractors and agents; or third parties with which You transact business.</p>
	<p>"<b>We</b>," "<b>Us</b>" or "<b>Our</b>" means the company (Who You Are Contracting With, Notices, Governing Law and Jurisdiction).</p>
	<p>"<b>You</b>" or "<b>Your</b>" means the individual, company and Affiliates of that company or entity or other legal entity for which you are accepting this Agreement. </p>
	<p>"<b>Your Data</b>" means all electronic data or information submitted by You. </p>
	<h4>2. PURCHASED SERVICES</h4>
	<p>If you purchase any services that we offer for a fee, either on a one-time or subscription basis (“Premium Services”), you agree to GINKO storing your payment card information. You also agree to pay the applicable fees for the Premium Services (including, without limitation, periodic fees for premium accounts) as they become due plus all related taxes, and to reimburse us for all collection costs and interest for any overdue amounts. Your obligation to pay fees continues through the date you cancel your subscription to the Premium Services. All fees and charges are nonrefundable and there are no refunds or credits for partially used periods. You also acknowledge that GINKO’s Premium Services are subject to this Agreement and any additional terms related to the provisions of the Premium Service. </p>
	<h4>3. USE OF THE SERVICES</h4>
	<h5>3.1 Your Rights. </h5>
	<p>On the condition that you comply with all your obligations under this Agreement, we grant you a limited, revocable, nonexclusive, nonassignable, nonsublicenseable right to access, through a generally available web browser or mobile device or application (but not through scraping, spidering, crawling or other technology or software used to access data without the express written consent of GINKO), view information and use the Services that we provide on GINKO webpages and in accordance with this Agreement. Any other use of GINKO contrary to our mission and purpose (such as seeking to connect to someone you do not know or trust, or to use information gathered from GINKO commercially unless expressly authorized by GINKO) is strictly prohibited and a violation of this Agreement. We reserve all rights not expressly granted in this Agreement, including, without limitation, title, ownership, intellectual property rights, and all other rights and interest in GINKO and all related items. </p>
	<h5>3.2 Your Responsibilities. </h5>
	<p>You shall (i) be responsible for Users’ compliance with this Agreement, (ii) be solely responsible for the accuracy, quality, integrity and legality of your data and of the means by which you acquired your data, (iii) use commercially reasonable efforts to prevent unauthorized access to or use of the Services, and notify Us promptly of any such unauthorized access or use, and (iv) use the Services only in accordance with these Terms and applicable laws and government regulations. You shall not (a) make the Services available to anyone other than yourself, (b) sell, resell, rent or lease the Services, (c) use the Services to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights, (d) use the Services to store or transmit Malicious Code, (e) interfere with or disrupt the integrity or performance of the Services or third-party data contained therein, or (f) attempt to gain unauthorized access to the Services or their related systems or networks. You shall keep your password secure and confidential and not permit others to use your account, refrain from using other Users’ accounts; and refrain from selling, trading, or otherwise transferring your GINKO account to another party.  Further, you are responsible for anything that happens through your account until you close down your account or prove that your account security was compromised due to no fault of your own. To close your account, please visit select settings from the GINKO app.</p>
	<h5>3.3  Our rights and obligations. </h5>
	<p>For as long as GINKO continues to offer the Services, GINKO shall provide and seek to update, improve and expand the Services. As a result, we allow you to access GINKO as it may exist and be available on any given day and have no other obligations, except as expressly stated in this Agreement. We may modify, replace, refuse access to, suspend or discontinue GINKO, partially or entirely, or change and modify prices for all or part of the Services in our sole discretion. All of these changes shall be effective upon their posting on our site or by direct communication to you unless otherwise noted. GINKO further reserves the right to withhold, remove and or discard any content available as part of your account, with or without notice if deemed by GINKO to be contrary to this Agreement. For avoidance of doubt, GINKO has no obligation to store, maintain or provide you a copy of any content that you or other Users provide when using the Services.</p>
	<p>You acknowledge, consent and agree that we may access, preserve, and disclose your registration and any other information you provide if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary in our opinion to: (1) comply with legal process, including but not limited to civil and criminal subpoenas, court orders or other compulsory disclosures; (2) enforce this Agreement; (3) respond to claims of a violation of the rights of third parties, whether or not the third party is a User, individual, or government agency; (4) respond to customer service inquiries; or (5) protect the rights, property, or personal safety of GINKO, our Users or the public. </p>
	<p>You are solely responsible for your interactions with other Users. GINKO may, in certain circumstances, prohibit you from contacting other Users through use of the Services or otherwise limit your use of the Services. GINKO reserves the right, but has no obligation, to monitor disputes between you and other members and to restrict, suspend, or close your account if GINKO determines, in our sole discretion, that doing so is necessary to enforce this Agreement. </p>
	<h5>3.4 Mobile Services.</h5>
	<p>GINKO may offer the Services through mobile applications created by Us or third party developers (“Platform Developers”). If you use the Services through a mobile device, you agree that information about your use of the Services through your mobile device and carrier may be communicated to us, including but not limited to your mobile carrier, your mobile device, or your physical location. In addition, use of the Services through a mobile device may cause data to be displayed on and through your mobile device. By accessing the Services using a mobile device, you represent that to the extent you import any of your GINKO data to your mobile device that you have authority to share the transferred data with your mobile carrier or other access provider. In the event you change or deactivate your mobile account, you must promptly update your GINKO account information to ensure that your messages are not sent to the person that acquires your old number and failure to do so is your responsibility. You acknowledge you are responsible for all charges and necessary permissions related to accessing GINKO through your mobile access provider. Therefore, you should check with your provider to find out if the Services are available and the terms for these services for your specific mobile devices. </p>
	<p>Finally, by using any downloadable application to enable your use of the Services, you are explicitly confirming your acceptance of the terms of the End User License Agreement associated with the application provided at download or installation, or as may be updated from time to time.</p>
	<h5>3.5  Privacy. </h5>
	<p>You should carefully read our full Privacy Policy before deciding to become a User as it governs our treatment of any information, including personally identifiable information you submit to us.</p>
	<h5>3.6  Contests and Sweepstakes. </h5>
	<p>GINKO may, from time to time, run different contests and sweepstakes based on each user’s use/interaction with the Service.  Ginko shall communicate to you, either through the Service or via email, the existence of any contest or sweepstakes as well as the location of the official rules.  By signing up for the Service, you agree to participate in any such contest or sweepstakes pursuant to the official rules.</p>
	<h4>4. THIRD-PARTY PROVIDERS</h4>
	<h5>4.1. Acquisition of Third-Party Products and Services. </h5>
	<p>We may offer Third-Party Applications. Any acquisition by You of third-party products or services, including but not limited to Third-Party Applications and implementation, customization and other consulting services, and any exchange of data between You and any third-party provider, is solely between You and the applicable third-party provider and You do so at your own risk. We do not warrant or support third-party products or services, whether or not they are designated by Us as “certified.” No purchase of third-party products or services is required to use the Services.</p>
	<h5>4.2. Third-Party Applications and Your Data.</h5>
	<p>If You install or enable Third-Party Applications for use with our Services, You acknowledge that We may allow providers of those Third-Party Applications to access Your Data as required for the interoperation of such Third-Party Applications with the Services. We shall not be responsible for any disclosure, modification or deletion of Your Data resulting from any such access by Third-Party Application providers. Our mobile or web-based software application for exchanging, displaying and managing contact information is patent pending.</p>
	<h4>5. PROPRIETARY RIGHTS</h4>
	<h5>5.1. Reservation of Rights.</h5>
	<p>Subject to the limited rights expressly granted hereunder, We reserve all rights, title and interest in and to the Services, including all related intellectual property rights. No rights are granted to You hereunder other than as expressly set forth herein.</p>
	<h5>5.2. Restrictions. </h5>
	<p>You shall not (i) permit any third party to access the Services except as permitted herein, (ii) create derivative works based on the Services, (iii) copy, frame or mirror any part or content of the Services, (iv) reverse engineer the Services, or (v) access the Services in order to (a) build a competitive product or service, or (b) copy any features, functions or graphics of the Services.</p>
	<h5>5.3. Ownership of Your Data.</h5>
	<p>As between Us and You, You exclusively own all rights, title and interest in and to all of Your Data, and may request its deletion at any time, unless you have shared information or content with others and they have not deleted it, or it was copied or stored by other users.</p>
	<h5>5.4. License and warranty for your submissions to GINKO.</h5>
	<p>You grant GINKO a nonexclusive, irrevocable, worldwide, perpetual, unlimited, assignable, sublicenseable, fully paid up and royalty-free right to us to copy, prepare derivative works of, improve, distribute, publish, remove, retain, add, process, analyze, use and commercialize, in any way now known or in the future discovered, any information you provide, directly or indirectly to GINKO, including but not limited to any user generated content, ideas, concepts, techniques or data to the services, you submit to GINKO, without any further consent, notice and/or compensation to you or to any third parties. Any information you submit to us is at your own risk of loss.</p>
	<p>By providing information to us, you represent and warrant that you are entitled to submit the information and that the information is accurate, not confidential, and not in violation of any contractual restrictions or other third party rights. It is your responsibility to keep your GINKO profile information accurate and updated.</p>
	<h5>5.5. Operation. </h5>
	<p>GINKO reserves complete and sole discretion with respect to the operation of the GINKO mobile application or website. GINKO may, among other things: (a) delete communications between members if it has not been accessed by a User within the time established by GINKO policies; (b) make available to third parties information relating to GINKO and Users; and (c) withdraw, suspend or discontinue any functionality or feature of GINKO. GINKO assumes no responsibility or liability for any content or activity, lawful or otherwise, occurring at any time on GINKO’s mobile application or website.</p>
	<p>GINKO may, in its complete and sole discretion, review uploaded information, data, files, conferences, BBSs, forums, and chats and authorize restrictions on access thereto. GINKO will not review the contents of email except as required by legal process.</p>
	<h5>5.6. Content.</h5>
	<p>Statements made in websites, newsgroups, message boards, email, forums, conferences and chats reflect only the views of their authors.  Forum managers, forum hosts, CPs, Advertisers, or Merchants appearing on GINKO are not authorized GINKO spokespersons, and their views do not necessarily reflect those of GINKO.</p>
	<h5>5.7. Copyright.</h5>
	<p>The entire contents of the GINKO mobile application and website are copyrighted as a collective work under the laws of United States and other copyright laws. GINKO holds the copyright in the collective work.</p>
	<p>You may display and, subject to any expressly stated restrictions or limitations relating to specific material, download portions of the material from the different areas of GINKO solely for your own non-commercial use, unless otherwise permitted. Any redistribution, retransmission or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner. You agree not to change or delete any proprietary notices from materials downloaded from GINKO.</p>
	<h5>5.8. Other Sites. </h5>
	<p>You are encouraged to use discretion while browsing the Internet on searches initiated at GINKO. GINKO links may lead unintentionally to sites containing information that some people may find inappropriate or offensive. Your use of third party links is at your own risk. It may also lead to sites which contain inaccurate information, false or misleading advertising, or information which violates copyright, libel or defamation laws. You agree that GINKO shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of, or reliance upon, any such content, goods or services available on or through any such Service or resource.</p>
	<h5>5.9. Review of Postings and Uploads.</h5>
	<p>GINKO does not and cannot review all communications and materials posted or uploaded to GINKO and are not responsible for the content of these communications and materials. However, GINKO reserves the right to block or remove communications or materials that it determines, upon being made aware of any matters it deems inappropriate, and in its sole discretion, to be (a) abusive, libelous, defamatory or obscene, (b) fraudulent, deceptive, or misleading, (c) in violation of a copyright or trademark, other intellectual property right of another or (d) offensive or otherwise unacceptable to GINKO.</p>
	<h5>5.10. On-line Communications.</h5>
	<p>Your participation in on-line communications occurs in real time and is not edited, censored, or otherwise controlled by GINKO. GINKO cannot and does not screen content provided by you to GINKO. In reserving the right to monitor these activities, GINKO assumes no responsibility or liability for any content or activity, lawful or otherwise, occurring at any time on GINKO.</p>
	<p>You are responsible for your communications and your use of GINKO. You may not, under any circumstances, do any of the following: (a) post or transmit any message which is libelous or defamatory; (b) post or transmit any message, data, image or program which is indecent, obscene or pornographic; (c) post or transmit any message, data, image or program that would violate the property rights of others, including unauthorized copyrighted text, images or programs, trade secrets or other confidential proprietary information, and trademarks or service marks used in an infringing fashion; (d) use GINKO to threaten, harass, stalk, abuse, or otherwise violate the legal rights (including rights of privacy and publicity) of others; (e) intercept or attempt to intercept email or other private communications not intended for you; (f) send email to Users or other Internet users for any purpose other than personal communication, including to advertise or offer to unsolicited sell goods or services to other Users, use as a mass unsolicited distribution medium to communicate a generally unsolicited message, or use your email account as an address to which Users or other Internet users need to respond (except as otherwise expressly permitted by GINKO; (g) send unsolicited email messages through third party mail servers in order to relay your email or hide the origination of your email to others; (h) upload or download files that contain software or other material protected by intellectual property laws, rights of privacy or publicity, or any other applicable law unless you own or control the rights to such files or have received all necessary consents; (i) upload files that contain a virus or corrupted data; (j) delete any author attributions, legal notices or proprietary designations or labels in a file that you upload to a BBS or GINKO; (k) falsify the source or origin of software or other material contained in a file that you upload to GINKO; (l) use GINKO in a manner that adversely affects the availability of its resources to other Users; (m) use, download or otherwise copy, or provide (whether or not for a fee) to a person or entity that is not a subscriber to GINKO the User directory or any portion thereof other than for personal, noncommercial purposes (except as otherwise expressly permitted by GINKO); (n) falsely purport to be an employee or agent of GINKO (o) cause repeated disruptive incidents; or (p) act, or fail to act, in your use of GINKO, in a manner that is contrary to applicable law or regulation.</p>
	<h5>5.11 DMCA Notifications of Claims of Infringements.</h5>
	<p>If you believe that your work has been copied in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please notify our agent for notice of claims of copyright or other intellectual property infringement ("Agent"), at our “Contact Us” page. Please provide our Agent with the following Notice: </p>
	<ul class="decimal_list">
		<li>Identify the material on our site that you claim is infringing, with enough detail so that we may locate it on the website;</li>
		<li>A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</li>
		<li>A statement by you declaring under penalty of perjury that (1) the above information in your Notice is accurate, and (2) that you are the owner of the copyright interest involved or that you are authorized to act on behalf of that owner;</li>
		<li>Your address, telephone number, and email address; and</li>
		<li>Your physical or electronic signature.</li>
	</ul>
	<p>We will remove the infringing posting(s), subject to the procedures outlined in the Digital Millennium Copyright Act (DMCA).</p>
	<h4>6. WARRANTIES AND DISCLAIMERS</h4>
	<h5>6.1. Mutual Warranties.</h5>
	<p>Each party represents and warrants that (i) it has the legal power to enter into this Agreement, and (ii) it will not transmit to the other party any Malicious Code (except for Malicious Code previously transmitted to the warranting party by the other party).</p>
	<h5>6.2. Disclaimer.</h5>
	<p>DO NOT RELY ON GINKO, ANY INFORMATION THEREIN, OR ITS CONTINUATION. WE PROVIDE THE PLATFORM FOR GINKO AND ALL INFORMATION AND SERVICES ON AN “AS IS” AND “AS AVAILABLE” BASIS. WE DO NOT PROVIDE ANY EXPRESS WARRANTIES OR REPRESENTATIONS.</p>
	<p>TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, WE DISCLAIM ANY AND ALL IMPLIED WARRANTIES AND REPRESENTATIONS, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT. IF YOU ARE DISSATISFIED OR HARMED BY GINKO OR ANYTHING RELATED TO GINKO, YOU MAY CLOSE YOUR GINKO ACCOUNT AND TERMINATE THIS AGREEMENT IN ACCORDANCE WITH SECTION 10 (“TERM & TERMINATION”) AND SUCH TERMINATION SHALL BE YOUR SOLE AND EXCLUSIVE REMEDY.</p>
	<p>GINKO IS NOT RESPONSIBLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES FOR THE DELIVERY OF ANY MESSAGES SENT THROUGH GINKO TO ANYONE. IN ADDITION, WE NEITHER WARRANT NOR REPRESENT THAT YOUR USE OF THE SERVICE WILL NOT INFRINGE THE RIGHTS OF THIRD PARTIES. ANY MATERIAL, SERVICE, OR TECHNOLOGY DESCRIBED OR USED ON THE MOBILE APP OR WEBSITE MAY BE SUBJECT TO INTELLECTUAL PROPERTY RIGHTS OWNED BY THIRD PARTIES WHO HAVE LICENSED SUCH MATERIAL TO US, SERVICE, OR TECHNOLOGY.</p>
	<p>GINKO DOES NOT HAVE ANY OBLIGATION TO VERIFY THE IDENTITY OF THE PERSONS SUBSCRIBING TO ITS SERVICES, NOR DOES IT HAVE ANY OBLIGATION TO MONITOR THE USE OF ITS SERVICES BY OTHER USERS OF THE COMMUNITY; THEREFORE, GINKO DISCLAIMS ALL LIABILITY FOR IDENTITY THEFT OR ANY OTHER MISUSE OF YOUR IDENTITY OR INFORMATION. 	</p>
	<p>GINKO DOES NOT GUARANTEE THAT THE SERVICES IT PROVIDES WILL FUNCTION WITHOUT INTERRUPTION OR ERRORS IN FUNCTIONING. IN PARTICULAR, THE OPERATION OF THE SERVICES MAY BE INTERRUPTED DUE TO MAINTENANCE, UPDATES, OR SYSTEM OR NETWORK FAILURES. GINKO DISCLAIMS ALL LIABILITY FOR DAMAGES CAUSED BY ANY SUCH INTERRUPTION OR ERRORS IN FUNCTIONING. FURTHERMORE, GINKO DISCLAIMS ALL LIABILITY FOR ANY MALFUNCTIONING, IMPOSSIBILITY OF ACCESS, OR POOR USE CONDITIONS OF THE GINKO SITE DUE TO INAPPROPRIATE EQUIPMENT, DISTURBANCES RELATED TO INTERNET SERVICE PROVIDERS, TO THE SATURATION OF THE INTERNET NETWORK, AND FOR ANY OTHER REASON.</p>
	<p>THE FOREGOING DISCLAIMERS SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
	<h4>7. INDEMNIFICATION</h4>
	<h5>7.1. Indemnification by You.</h5>
	<p>You shall defend Us against any Claim made or brought against Us by a third party alleging that Your Data, or Your use of the Services in violation of this Agreement, infringes or misappropriates the intellectual property rights of a third party or violates applicable law, and shall indemnify Us for any damages finally awarded against, and for reasonable attorney’s fees incurred by Us in connection with any such Claim; provided, that We (a) promptly give You written notice of the Claim; (b) give You sole control of the defense and settlement of the Claim (provided that You may not settle any Claim unless the settlement unconditionally release Us of all liability); and (c) provide to You all reasonable assistance, at Our expense.</p>
	<h4>8. LIMITATION OF LIABILITY</h4>
	<h5>8.1. Limitation of Liability.</h5>
	<p>NEITHER GINKO NOR ANY OF OUR SUBSIDIARIES, AFFILIATED COMPANIES, EMPLOYEES, SHAREHOLDERS, AGENTS OR DIRECTORS (“GINKO AFFILIATES”) SHALL BE LIABLE FOR (A) ANY DAMAGES IN EXCESS OF FIVE TIMES THE MOST RECENT MONTHLY FEE THAT YOU PAID FOR A PREMIUM SERVICE, IF ANY, OR US $25, WHICHEVER AMOUNT IS GREATER, OR (B) ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES OR LOSS OF USE, PROFIT, REVENUE OR DATA TO YOU OR ANY THIRD PERSON ARISING FROM YOUR USE OF THE SERVICE, ANY PLATFORM APPLICATIONS OR ANY OF THE CONTENT OR OTHER MATERIALS ON, ACCESSED THROUGH OR DOWNLOADED FROM GINKO. THIS LIMITATION OF LIABILITY SHALL:</p>
	<p>APPLY REGARDLESS OF WHETHER (1) YOU BASE YOUR CLAIM ON CONTRACT, TORT, STATUTE OR ANY OTHER LEGAL THEORY, (2) WE KNEW OR SHOULD HAVE KNOWN ABOUT THE POSSIBILITY OF SUCH DAMAGES, OR (3) THE LIMITED REMEDIES PROVIDED IN THIS SECTION FAIL OF THEIR ESSENTIAL PURPOSE; AND</p>
	<p>NOT APPLY TO ANY DAMAGE THAT GINKO MAY CAUSE YOU INTENTIONALLY OR KNOWINGLY IN VIOLATION OF THIS AGREEMENT OR APPLICABLE LAW, OR AS OTHERWISE MANDATED BY APPLICABLE LAW THAT CANNOT BE DISCLAIMED FROM IN THIS AGREEMENT.</p>
	<h4>9. TERM AND TERMINATION</h4>
	<p>The Terms apply to all users of the GINKO.  Except as described below, you can discontinue your use of GINKO so that these Terms of Use no longer apply to you.</p>
	<h5>9.1. Term of Agreement.</h5>
	<p>This Agreement commences on the date You accept it and continues until all User subscriptions granted in accordance with this Agreement have expired or been terminated.</p>
	<h5>9.2. Termination.</h5>
	<p>If you use any of the GINKO services (or parts of those services) as a user, you may terminate your user account at any time. Doing so will delete your account and, because you can no longer use the service associated with that account, will terminate the Terms of Use with respect to that service. If you breach any provision of these Terms of Use or other applicable policies, or for any other reason, GINKO reserves the right to restrict, suspend, or terminate your user account(s) for any or all of GINKO services and terminate the Terms of Use. We may take these actions with or without notice to you.  We will generally use reasonable efforts to give notice of these actions.</p>
	<p>GINKO may restrict, suspend or terminate the account of any User who abuses or misuses the Services. Misuse of the Services includes inviting other Users with whom you do not know to connect; abusing the GINKO messaging services; creating multiple or false profiles; using the Services commercially without GINKO’s authorization, infringing any intellectual property rights, or any other behavior that GINKO, in its sole discretion, deems contrary to its purpose. In addition, and without limiting the foregoing, GINKO has adopted a policy of terminating accounts of Users who, in GINKO’s sole discretion, are deemed to be repeat infringers under the United States Copyright Act. </p>
	<p>Upon the termination of your GINKO account, you lose access to the Services. In addition, GINKO may block access to the Services from an IP address or range of IP addresses associated with those of terminated Users.</p>
	<p>Sections 5, 6, 7, 8 and 9 of these Terms will survive termination, and shall continue to apply indefinitely.</p>
	<h4>10. NOTICE</h4>
	<h5>10.1. General.</h5>
	<p>Who You are contracting with under this Agreement, who You should direct notices to under this Agreement, what law will apply in any lawsuit arising out of or in connection with this Agreement, and which courts can adjudicate any such lawsuit, shall be governed by and construed in accordance with the laws of the State of Michigan. You agree that any legal action or proceeding between GINKO and you for any purpose concerning this Agreement or the parties' obligations hereunder shall be brought exclusively in a court of competent jurisdiction for Wayne County, Michigan, United States. Any cause of action or claim you may have with respect to GINKO must be commenced within sixty (60) days after the claim or cause of action arises. GINKO will have thirty (30) days to rectify the situation. GINKO's failure to insist upon or enforce strict performance of any provision of this Agreement shall not be construed as a waiver of any provision or right. Neither the course of conduct between the parties nor trade practice shall act to modify any provision of this Agreement. GINKO may assign its rights and duties under this Agreement to any party at any time without notice to you.</p>
	<h5>10.2. Manner of Giving Notice.</h5>
	<p>Except as otherwise specified in this Agreement, all notices, permissions and approvals hereunder shall be in writing and shall be deemed to have been given upon: (i) personal delivery, (ii) the second business day after mailing, (iii) the second business day after sending by confirmed facsimile, or (iv) the first business day after sending by email (provided email shall not be sufficient for notices of an indemnifiable claim). Notices to You shall be addressed to the system administrator designated by You for Your relevant Services account, and in the case of billing-related notices, to the relevant billing contact designated by You.</p>
	<p>Notices should be sent to:</p>
	<p>Email:  inquiries@ginko.mobi </p>
	<p>The governing law is: Michigan and controlling United States federal law</p>
	<p>The courts having exclusive jurisdiction are: Michigan, U.S.A.</p>
	<h5>10.3. Agreement to Governing Law and Jurisdiction.</h5>
	<p>Each party agrees to the applicable governing law above without regard to choice or conflicts of law rules, and to the exclusive jurisdiction of the applicable courts above.</p>
	<h5>10.4. Waiver of Jury Trial. </h5>
	<p>Each party hereby waives any right to jury trial in connection with any action or litigation in any way arising out of or related to this Agreement.</p>
	<h5>10.5 Mandatory Arbitration. </h5>
	<p>Any Disputes shall be resolved by mandatory final and binding arbitration under the rules and auspices of the American Arbitration Association, to be held in Detroit, Michigan, in English, with a written decision stating and legal reasoning issued by the arbitrator(s) at either party’s request, and with arbitration costs and reasonable documented attorneys’ fees and costs of both parties to be borne by the party that ultimately loses. If a disputed issue is not resolved within ten (10) days, then the resolution of the dispute shall be referred to an Arbitrator chosen by the parties. If the parties are unable to resolve any dispute with the assistance of the Arbitrator within fifteen (15) days of the appointment thereof, the dispute shall be settled by arbitration. The award of the arbitration shall be final and binding upon the parties, and enforceable in any court of competent jurisdiction. The venue for any arbitration hereunder shall be Wayne County, Michigan.</p>
	<h4>11. GENERAL PROVISIONS</h4>
	<h5>11.1. Export Compliance.</h5>
	<p>Each party shall comply with the export laws and regulations of the United States and other applicable jurisdictions in providing and using the Services. Without limiting the foregoing, (i) each party represents that it is not named on any U.S. government list of persons or entities prohibited from receiving exports, and (ii) You shall not permit Users to access or use Services in violation of any U.S. export embargo, prohibition or restriction.</p>
	<h5>11.2. Relationship of the Parties.</h5>
	<p>This Agreement does not create a partnership, franchise, joint venture, agency, and fiduciary or employment relationship between the parties.</p>
	<h5>11.3. No Third-Party Beneficiaries.</h5>
	<p>Entities other than GINKO LLC that GINKO LLC owns a 50% or greater interest in (“Affiliate”) are not parties, but intended third party beneficiaries of this Agreement, with a right to enforce the Agreement directly against you. </p>
	<h5>11.4. Waiver.</h5>
	<p>Our failure to act with respect to a breach of this Agreement by you or others does not waive our right to act with respect to that breach or subsequent similar or other breaches. Except as expressly and specifically contemplated by the Agreement, no representations, statements, consents, waivers or other acts or omissions by any GINKO Affiliate shall be deemed legally binding on any GINKO Affiliate, unless documented in a physical writing hand signed by a duly appointed officer of GINKO.</p>
	<h5>11.5. Severability. </h5>
	<p>If any provision of this Agreement is held by a court of competent jurisdiction to be contrary to law, the provision shall be modified by the court and interpreted so as best to accomplish the objectives of the original provision to the fullest extent permitted by law, and the remaining provisions of this Agreement shall remain in effect.</p>
	<h5>11.6. Attorney Fees.</h5>
	<p>You shall pay on demand all of Our reasonable attorney fees and other costs incurred by Us to collect any fees or charges due Us under this Agreement following Your breach.</p>
	<h5>11.7 Language.</h5>
	<p>Where GINKO has provided you with a translation of the English language version of this Agreement, the Privacy Policy, and/or any other documentation, you agree that the translation is provided for your convenience only and that the English language versions of this Agreement, the Privacy Policy, and any other documentation, including additional terms of service for Premium Services, will govern your relationship with GINKO.</p>
	<h5>11.8 No Injunctive Relief.</h5>
	<p>In no event shall you seek or be entitled to rescission, injunctive or other equitable relief, or to enjoin or restrain the operation of the Service, exploitation of any advertising or other materials issued in connection therewith, or exploitation of the Services or any content or other material used or displayed through the Services.</p>
	<h5>11.9 Assignment and Delegation.</h5>
	<p>You may not assign or delegate any rights or obligations under the Agreement. Any purported assignment and delegation shall be ineffective. We may freely assign or delegate all rights and obligations under the Agreement, fully or partially without notice to you. We may also substitute, by way of unilateral novation, effective upon notice to you, GINKO Corporation for any third party that assumes our rights and obligations under this Agreement.</p>
	<h5>11.10 Entire Agreement.</h5>
	<p>You agree that this Agreement constitutes the entire, complete and exclusive agreement between you and us regarding the Services and supersedes all prior agreements and understandings, whether written or oral, or whether established by custom, practice, policy or precedent, with respect to the subject matter of this Agreement. You also may be subject to additional terms and conditions that may apply when you use or purchase certain other GINKO services, third-party content or third party software.</p>
	<h5>11.11 Amendments to this Agreement.</h5>
	<p>We reserve the right to modify, supplement or replace the terms of the Agreement, effective upon posting at www.ginko.mobi or notifying you otherwise. If you do not want to agree to changes to the Agreement, you can terminate the Agreement at any time per Section 9 (Term & Termination).</p>
</div>

<div style = 'background-color:#89cb60; height:10vw; bottom:18vw; margin-top: -3vw;' class = 'full-width' align = 'center'>
  <table style="width:100%;text-align: center;font-size: 2vw;color:white;padding-bottom:3%;padding-top:2.2%;font-family:HelveticaLight">
    <tbody>
      <tr>
        <td style = 'width: 25%;cursor:pointer;'><a href="<?php echo base_url(); ?>officialrules" style="color: white; text-decoration: none;">Official Rules</a></td>
        <td style = 'width: 25%;border-right:1px solid white;border-left:1px solid white;cursor:pointer;'><a href="<?php echo base_url(); ?>terms" style="color: white; text-decoration: none;">Terms of Use</a></td>
        <td style = 'width: 25%;border-right:1px solid white;cursor:pointer;'><a href="<?php echo base_url(); ?>privacypolicy" style="color: white; text-decoration: none;">Privacy Policy</a></td>
        <td style = 'width: 25%;cursor:pointer;'><a href="<?php echo base_url(); ?>aboutus" style="color: white; text-decoration: none;">About Us</a></td>
      </tr>
    </tbody>
  </table>
</div>
<div style = 'background-color:white; height:18vw; bottom:0px; ' class = 'full-width' align = 'center'>

	<table style="width:80%;text-align: center;font-size: 2vw;color:white;padding-top:0px; padding-bottom:0px">
    <tbody>
      <tr>
        <td style = 'text-align:right'><a href = 'https://itunes.apple.com/us/app/ginko/id1029413955?ls=1&mt=8'><img src = "<?php echo base_url(WEB_IMAGES.'footer 1.png');?>" style = 'width:50%'></a></td>
        <td style = 'text-align:left'><a href = 'https://play.google.com/store/apps/details?id=com.ginko.ginko'><img src = "<?php echo base_url(WEB_IMAGES.'footer 2.png');?>" style = 'width:50%'></a></td>
      </tr>
      <tr>
      	<td colspan = 2 align = 'center'>
        	
            <div class = 'cell_content' style = 'font-size:2vw; color:black;display:block'>
            	Ginko LLC © 2014
            </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>	

